title: DFMTTS-Phoneme-DiT-(steps-${trainer.max_steps})-(bs-${train.batch_size})-(LR-${optimizer.params.learning_rate})-(wd-${optimizer.params.weight_decay})-(kappa-${kappa_scheduler.a}-${kappa_scheduler.b})-(length_loss-${model.length_loss_weight})-(max_length-${datasets.max_length})

datasets:
    train_metadata: "/hadatasets/alef.ferreira/DATASETS/LibriTTS_R-Wavtokenizer/train.csv"
    val_metadata: "/hadatasets/alef.ferreira/DATASETS/LibriTTS_R-Wavtokenizer/val.csv"

    text_column: "text"
    phonemes_column: "phonemes"
    token_column: "filepath"
    language_column: "language"

    use_phonemes: true

    audio_pad_token: 4096
    audio_mask_token: 4097

    vocab_path: "../config/vocab.json"
    max_length: 2048 # Aprox. 50 seconds of audio (40 tokens/second)
    text_vocab_size: 178
    audio_vocab_size: 4098

model:
    type: "dit" # dit, transformer
    audio_drop_prob: 0.3
    cond_drop_prob: 0.2

    length_loss_weight: 0.1

    DIT:
        dim: 1024
        depth: 22
        heads: 16
        dim_head: 64
        dropout: 0.1
        ff_mult: 0.2
        text_dim: 512
        audio_dim: 512
        text_conv_layers: 4
        audio_conv_layers: 4

wavtokenizer:
    config_path: "WavTokenizer/configs/wavtokenizer_smalldata_frame40_3s_nq1_code4096_dim512_kmeans200_attn.yaml"
    model_path: "/hadatasets/alef.ferreira/DFM-TTS/checkpoints/WavTokenizer_small_600_24k_4096.ckpt"

coupling:
    mask_prob: 0.15
    min_mask_prob: 0.4
    max_mask_prob: 1.0

kappa_scheduler:
    a: 0.0 # 2.0
    b: 2.0 # 0.5

train:
    batch_size: 8
    shuffle: True
    num_workers: 12

optimizer:
    name: "adamw"
    params:
        min_learning_rate: 1e-5
        learning_rate: 5e-5
        eps: 1e-8
        weight_decay: 1e-4
        betas: [0.9, 0.999]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 2500

tags:
    - Discrete Flow Matching
    - ${trainer.max_steps}-max_steps
    - LibriTTS-R
    - Wavtokenizer
    - ${train.batch_size}-BS
    - LR-${optimizer.params.learning_rate}

trainer:
    accelerator: "gpu"
    max_steps: 720000 # Aprox. 100 epochs
    num_sanity_val_steps: 0
    overfit_batches: 0.0
    log_every_n_steps: 10
    val_check_interval: 1000
    gradient_clip_val: 2.0
    gradient_clip_algorithm: "norm"
    accumulate_grad_batches: 4

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: false
    monitor: "val/total_loss"
    dirpath: "../checkpoints/DFMTTS"
    filename: "{epoch:02d}-{step:02d}-{val/total_loss:.3f}"

test:
    log_audio_ref: true
    steps: 128
    audio_tokens_ref_path: "/hadatasets/alef.ferreira/DATASETS/LibriTTS_R-wavtokenizer-dev-clean/6295/64301/6295_64301_000007_000003.pt"
    audio_ref_path: "/hadatasets/alef.ferreira/DATASETS/LibriTTS_R-dev-clean/6295/64301/6295_64301_000007_000003.wav"
    text_ref: "O my God-through the mud of me, up to thy righteousness!"
    sentences:
        - "Now, as all books not primarily intended as picture-books consist principally of types composed to form letterpress"
        - "There is no way, however, to eliminate the possibility of the fibers having come from another identical shirt, end quote"
        - "Oswald's Marine training in marksmanship, his other rifle experience and his established familiarity with this particular weapon"
        - "Nevertheless, she attempted to commit suicide by driving her nails, purposely left long, into her throat."
        - "His being was like an all sided lens concentrating all joys in the one heart of his consciousness."
        - "When he reached Mary's shop, he turned into the court to the kitchen door."