CUDA_VISIBLE_DEVICES=6 python /raid/aluno_alef/DFM-TTS-2/src/infer_librispeech_v6_pfg_tsr_remask.py \
    --config="/raid/aluno_alef/DFM-TTS-2/config/emilia/en-eos_as_pad-gpt2-emilia_yodas-mask-ce-poly-variable_window-c_coupling-pfg.yaml" \
    --checkpoint="/raid/aluno_alef/DFM-TTS-2/src/DFM-TTS/yrwxs6l7/checkpoints/epoch=01-step=880000-val/loss_epoch=3.937.ckpt" \
    --metadata_csv="/raid/aluno_alef/DATASETS/LibriSpeech-test-clean-filtered.csv" \
    --output_dir="/raid/aluno_alef/DFM-TTS-2/src/output_infer/yrwxs6l7_remdm_best_tsr_best" \
    --use_oracle_length \
    --oracle_add_eos \
    --nsf=2,4,8,16,32,64,128 \
    --use_pfg \
    --gamma=1.5 \
    --use_remdm \
    --remdm_eta_rescale 0.5 \
    --remdm_eta_cap 0.5 \
    --remdm_tswitch 0.0 \
    --use_tsr \
    --tsr_k=3.0 \
    --tsr_sigma=2.0